#!/usr/bin/env python3
#
# output the C code needed for building c_longhand
# 
# SPDX-License-Identifier: GPL-2.0-only


for i in range(1,101):
    if i % 3 == 0 and i % 5 == 0:
        output = "fizzbuzz"
    elif i % 3 == 0:
        output = "fizz"
    elif i % 5 == 0:
        output = "buzz"
    else:
        output = f"{i}"

    print(f'    if (i == {i}) printf("{output}\\n");')
