#!/usr/bin/env python3

for i in range(1, 101):
    this = ""

    fizz = (3 - i % 3) - 2
    this += "fizz"*fizz

    buzz = (5 - i % 5) - 4
    this += "buzz"*buzz

    numstr = str(i)
    this += numstr * (-len(this)+1)
    print(this)
